# Practising workflows with branch protection

name: Lint when Pull Request

on:
    pull_request:
        branches:
            - main

env:
    NODE_VERSION: 18

jobs:

    linting: 
        name: Linting
        runs-on: ubuntu-latest
        steps:

            - name: Install NodeJs
              uses: actions/setup-node@v4
              with: 
                node-version: ${{env.NODE_VERSION}}

            - name: Code checkout
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm ci

            - name: Code linting
              run: npm run lint


